### ISSUE TITLE
Cannot load DTD file properly

### ISSUE THREAD

**Issue by TisonKun** [JuliaIO/LightXML.jl#82]
```
dblp.xml:3795634: parser error : Detected an entity reference loop
true_main at /usr/local/bin/julia (unknown line)
<author>Br&aacute;ulio Coelho &Aacute;vila</author>
```

```
$ ls
dblp.dtd dblp.xml
$ head dblp.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE dblp SYSTEM "dblp.dtd">
<dblp>
<article mdate="2017-05-28" key="journals/acta/Saxena96">
<author>Sanjeev Saxena</author>
<title>Parallel Integer Sorting and Simulation Amongst CRCW Models.</title>
<pages>607-619</pages>
<year>1996</year>
<volume>33</volume>
<journal>Acta Inf.</journal>
```

```
$ cat parse.jl 
using LightXML

doc = parse_file("dblp.xml")
```

Or how can I config DTD file?

**Comment by jlegare** [comment]
Would you be able to provide your DTD (dblp.dtd)? I have not been able to reproduce this issue in the following two cases: a trivial single-element DTD (see test001 in attached ZIP file), and a DTD I monkeyed up to validate your partial input (see my dblp, attached ... which I am not claiming is correct for all your inputs). 

[Archive.zip](https://github.com/JuliaIO/LightXML.jl/files/2300408/Archive.zip)

**Comment by TisonKun** [comment]
@jlegare the main issue is about decode HTML character like `&aacute;`.

I think you can reproduce it by download dblp.xml and dblp.dtd [here](https://dblp.uni-trier.de/xml/). It is over hundred MB thus not upload here.

**Comment by TisonKun** [comment]
[dblp.dtd.zip](https://github.com/JuliaIO/LightXML.jl/files/2342028/dblp.dtd.zip)

**Comment by jlegare** [comment]
Yes I see the problem now. Sorry for not catching on earlier. To the best of my knowledge, LightXML does not do a validating parse, only a well-formed parse: see src/document.jl in the source tree. LightXML calls xmlParseFile in libxml2, which according to http://xmlsoft.org/html/libxml-parser.html#xmlParseFile only does a well-formedness check. I traced through the source for libxml2 (see https://github.com/GNOME/libxml2/blob/bfec41b3de1cbd35e547b57c80ae3a5101f8891c/parser.c#L14231 and then trace the function calls), and again it appears to only be doing a well-formed parse. So it reads through the DTD (checking for syntax), but does not use any of the information contained therein. Specifically it does not use your entity declarations. When parsing the instance therefore, the HTML entities (e.g., &eacute;) are considered in error, since well-formed parsing requires entities to be declared. I have also read of a memory limit imposed in libxml2 that triggers the "circular entity" message you gave in your first post: this memory limit caused undeclared entities to eventually be reported as circular definitions.

You could pre-process your input to replace entities with their numerical equivalents. If I have time over the next few days, I could try to write this up for you, but it may be a few days in coming, and also this may not be an appropriate solution for you. Alternatively, a validating parse entry point could be added to LightXML, but I don't know if the maintainers consider this to be out-of-scope for the project.

Sorry I couldn't be of more help.

**Comment by jlegare** [comment]
(I just discovered that GitHub apparently does entity replacement. The &eacute; in my posting above was supposed to be &amp;eacute;, not its replacement.)

**Comment by jlegare** [comment]
I did a little additional digging. It seems you can do a validating parse with LightXML if you use the second form of `parse_file`, where you specify the encoding and additional options that are passed down to the C code:

`parse_file("dblp.xml", C_NULL, 0x4 | 0x10)`

I haven't tried this with the full sample, but this eliminates the errors about entities in a trimmed down sample. The options are described (admittedly quite briefly) here

http://xmlsoft.org/html/libxml-parser.html#xmlParserOption

You can actually get away with just `0x4` ... load the external subset but don't actually use it for validation.

**Comment by TisonKun** [comment]
Close as no longer interested.
